# Generated by Django 3.2.9 on 2021-11-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211126_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantprice',
            name='product_variant_one',
        ),
        migrations.RemoveField(
            model_name='productvariantprice',
            name='product_variant_three',
        ),
        migrations.RemoveField(
            model_name='productvariantprice',
            name='product_variant_two',
        ),
    ]
